### ISSUE TITLE
delete an entire order

### ISSUE THREAD

**Issue by PillowBitch** [klarstrup/wip-pos#9]
Do it then. Oh you think you're a tough þuy, huh? Fucking do it then, delete it. Yes, the entire order. See if I care 😠

**Comment by PillowBitch** [comment]
Also make it so the page will ask for confirmation when closed / refreshed if an order is open

**Comment by klarstrup** [comment]
closed by https://github.com/klarstrup/wip-pos/commit/2a549a42901830062470fc85fed483242d3732d2
